version: '3.9'

services:
  web:
    build: .
    depends_on:
      -  postgres
    ports:
      - "80:80"
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: nivos